# compose.yaml
---
include:    
  - mutillidae-dockerhub/docker-compose.yml
#  - juice-shop-compose.yaml
#  - webgoat-compose.yaml

services:
  dvwa:
    image: sagikazarmark/dvwa
    ports:
      - 8080:80
      - 3306:3306
    volumes:
      - dvwadb:/var/lib/mysql

volumes:
  dvwadb:
