# deploy.yaml
---
- name: "Linux Cible"
  hosts: Cibles
  become: true
  vars:
    ansible_sudo_pass: S0l&il01 # Mettre votre mot de passe

  pre_tasks:
    - name: INSTALL DEPENDANCES DOCKER
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      tags: docker
    - name: AJOUT CLE GPG DE DOCKER
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: docker
    - name: AJOUT DEPOT APT DE DOCKER
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
      tags: docker
    - name: INSTALL DOCKER
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags: docker
    - name: DEMARRE DOCKER
      ansible.builtin.systemd_service:
        state: started
        name: docker
      tags: docker

    - name: Creer repertoire pour les applications
      ansible.builtin.file:
        path: /home/jim/webapp/
        state: directory
        owner: jim
        group: jim
        mode: 0775
      tags: reps
    - name: Creer repertoire pour Mutillidae
      ansible.builtin.file:
        path: /home/jim/webapp/mutillidae-dockerhub
        state: directory
        owner: jim
        group: jim
        mode: 0775
      tags: reps

  tasks:
    - name: Clone mutillidae
      ansible.builtin.git:
        repo: 'https://github.com/webpwnized/mutillidae-dockerhub.git'
        dest: /home/jim/webapp/mutillidae-dockerhub
      tags: clone_git
    - name: Copie fichier docker-compose pour mutillidae
      copy:
        src: ./conf/docker-compose.yml
        dest: /home/jim/webapp/mutillidae-dockerhub/docker-compose.yml
        mode: 0755
      tags: copy_files
    - name: Copie fichier compose.yaml
      copy:
        src: ./conf/compose.yaml
        dest: /home/jim/webapp/compose.yaml
        mode: 0755
      tags: copy_files
    - name: Copie fichier juice-shop-compose.yaml
      copy:
        src: ./conf/juice-shop-compose.yaml
        dest: /home/jim/webapp/juice-shop-compose.yaml
        mode: 0755
      tags: copy_files
    - name: Copie fichier juice-shop-compose.yaml
      copy:
        src: ./conf/metasploitable2-compose.yaml
        dest: /home/jim/webapp/metasploitable2-compose.yaml
        mode: 0755
      tags: copy_files
      copy:
        src: ./conf/webgoat-compose.yaml
        dest: /home/jim/webapp/webgoat-compose.yaml
        mode: 0755
      tags: copy_files


    - name: Run 'docker compose down'
      community.docker.docker_compose_v2:
        project_src: /home/jim/webapp
        state: absent
      tags: compose_down

    - name: Run 'docker compose up'
      community.docker.docker_compose_v2:
        project_src: /home/jim/webapp
      register: output
      tags: compose_up
    - name: Afficher resultat du lancement des services
      ansible.builtin.debug:
        var: output
      tags: compose_up

    - name: Arret des services 'docker compose stop'
      community.docker.docker_compose_v2:
        project_src: /home/jim/webapp
        state: stopped
      register: output
      tags: compose_stop
    - name: Afficher resultat du stop des services
      ansible.builtin.debug:
        var: output
      tags: compose_stop
    - name: Verifie que les services dvwa et www sont arret
      ansible.builtin.assert:
        that:
          - dvwa_container.State != 'running'
          - www_container.State != 'running'
      vars:
        dvwa_container: >-
          {{ output.containers | selectattr("Service", "equalto", "dvwa") | first }}
        www_container: >-
          {{ output.containers | selectattr("Service", "equalto", "www") | first }}
      tags: compose_stop

    - name: Repart les services 'docker compose restart'
      community.docker.docker_compose_v2:
        project_src: /home/jim/webapp
        state: restarted
      register: output
      tags: compose_restart
    - name: Afficher resultat du stop des services
      ansible.builtin.debug:
        var: output
      tags: compose_restart
    - name: Verifie que les services dvwa et www sont parties
      ansible.builtin.assert:
        that:
          - dvwa_container.State == 'running'
          - www_container.State == 'running'
      vars:
        dvwa_container: >-
          {{ output.containers | selectattr("Service", "equalto", "dvwa") | first }}
        www_container: >-
          {{ output.containers | selectattr("Service", "equalto", "www") | first }}
      tags: compose_restart
