# hosts.yaml
---
all:
  hosts:
    control:
      ansible_connection: local

Cibles:
  hosts:
    linux-cible:
      ansible_host: 192.168.11.116
      ansible_ssh_private_key_file: /Users/clroy/.ssh/linuxcible

